CREATE TABLE MEMBER
(
SSN INT,
NAME VARCHAR(50),
HOME_ADDRESS VARCHAR(1000),
CAMPUS_ADDRESS VARCHAR(1000),
PHONE_NO VARCHAR(50),
MEMBER_TYPE VARCHAR(50),
GRACE_PERIOD INT,
BORROW_PERIOD INT, 
EMPLOYEE_TYPE VARCHAR(50),
STAFF_TYPE VARCHAR(50),
PRIMARY KEY(SSN)
);

CREATE TABLE BOOK
(
ISBN INT,
TITLE VARCHAR(100),
BINDING VARCHAR(20),
LANGUAGE VARCHAR(100),
EDITION VARCHAR(30),
AUTHOR VARCHAR(50),
DESCRIPTION LONGTEXT,
VOLUME VARCHAR(30),
SUBJECT_AREA VARCHAR(100),
BOOK_TYPE VARCHAR(30),
AVAILABILITY CHAR(1) NOT NULL CHECK(AVAILABILITY IN('Y', 'N')),
STATUS_TYPE VARCHAR(30),
PRIMARY KEY(ISBN)
);

CREATE TABLE CARD
(
CARD_ID INT,
PHOTO BLOB,
ISSUE_DATE DATE,
EXPIRY_DATE DATE,
VALIDITY DATE,
M_SSN INT,
PRIMARY KEY (CARD_ID),
FOREIGN KEY (M_SSN) REFERENCES MEMBER(SSN) ON DELETE CASCADE
);

CREATE TABLE COPY( 
BOOK_ID INT, 
ISBN INT NOT NULL, 
STATUS VARCHAR(20), 
PRIMARY KEY(BOOK_ID),
FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE
);

CREATE TABLE BORROW
(
BOOK_ID INT,
M_SSN INT,
ISSUED_BY INT,
ISSUE_DATE DATE,
DUE_DATE DATE,
RETURN_DATE DATE,
GRACE_PERIOD DATE,
STATUS VARCHAR(20),
PRIMARY KEY(BOOK_ID,M_SSN,ISSUE_DATE),
FOREIGN KEY(BOOK_ID) REFERENCES COPY(BOOK_ID),
FOREIGN KEY(M_SSN) REFERENCES MEMBER(SSN),
FOREIGN KEY(ISSUED_BY) REFERENCES MEMBER(SSN)
);

CREATE TABLE VISITS
(
M_SSN INT,
CHECK_IN DATE,
CHECK_OUT DATE,
NAME VARCHAR(50),
PASS_ID INT,
VISITOR_TYPE VARCHAR(50),
VALIDITY_DATE DATE,
PRIMARY KEY (M_SSN,CHECK_IN),
FOREIGN KEY (M_SSN)REFERENCES MEMBER(SSN)
);